/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32l031xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void GPIOInits(void)
{
	GPIO_Handler_t CLK_LCD_PINS;

	CLK_LCD_PINS.pGPIOx = GPIOB;

	CLK_LCD_PINS.GPIO_PinConfig.GPIO_PinMode = OUTPUT;
	CLK_LCD_PINS.GPIO_PinConfig.GPIO_PinAltFunMode = AF0;
	CLK_LCD_PINS.GPIO_PinConfig.GPIO_PinOPType = PUSHPULL;
	CLK_LCD_PINS.GPIO_PinConfig.GPIO_pinPuPdControl = PULLDOWN;
	CLK_LCD_PINS.GPIO_PinConfig.GPIO_PinSpeed = SPEEDHIGH;

	CLK_LCD_PINS.GPIO_PinConfig.GPIO_PinNumber = 3;
	GPIO_Init(&CLK_LCD_PINS);

}

int main(void)
{
	GPIOInits();

	while(1)
	{
		//GPIO_ToggleOutputPin(GPIOB,3);
		GPIO_WriteToOutputPin(GPIOB, 3, ENABLE);
	}
}
